apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: test
  name: prometheus-demo
  labels:
    app: prometheus-demo

spec:
  replicas: 2
  selector:
    matchLabels:
      app: prometheus-demo
  template:
    metadata:
      labels:
        app: prometheus-demo
    spec:
      containers:
        - name: prometheus-demo
          image: 192.168.164.60:80/repo/prometheus-demo:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  namespace: test
  labels:
    app: prometheus-demo
  name: prometheus-demo

spec:
  selector:
    app: prometheus-demo
  ports:
    - port: 8081
      targetPort: 8080
  type: NodePort

